### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by emptywalker** [alibaba/weex-ui#116]
```
node v8.4.0
npm v5.5.1
weex -v
   v1.1.0-beta.7
 - weexpack : v0.4.7-beta.26
 - weex-builder : v0.2.13-beta.4
 - weex-devtool : v0.3.2-beta.11
 - weex-previewer : v1.3.13-beta.10
```
在以上环境下，执行`npm i babel-plugin-component babel-preset-stage-0 -D`报错如下:
```
npm i babel-plugin-component babel-preset-stage-0 -D
npm ERR! code E403
npm ERR! 403 Forbidden: @babel/helper-module-imports@7.0.0-beta.35

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/emptywalker/.npm/_logs/2018-01-09T08_22_19_396Z-debug.log
```

log内容如下：
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   'babel-plugin-component',
1 verbose cli   'babel-preset-stage-0',
1 verbose cli   '-D' ]
2 info using npm@5.5.1
3 info using node@v8.4.0
4 verbose npm-session ebc679618061f9f9
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 http://npm.showjoy.net/babel-preset-stage-0 1792ms
8 http fetch GET 200 http://npm.showjoy.net/babel-plugin-component 1801ms
9 silly pacote tag manifest for babel-preset-stage-0@latest fetched in 1798ms
10 silly pacote tag manifest for babel-plugin-component@latest fetched in 1837ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 silly install loadShrinkwrap
14 silly install loadAllDepsIntoIdealTree
15 silly resolveWithNewModule babel-preset-stage-0@6.24.1 checking installable status
16 silly resolveWithNewModule babel-plugin-component@1.0.0 checking installable status
17 http fetch GET 403 http://npm.showjoy.net/@babel%2fhelper-module-imports 53ms
18 silly fetchPackageMetaData error for @babel/helper-module-imports@7.0.0-beta.35 403 Forbidden: @babel/helper-module-imports@7.0.0-beta.35
19 verbose stack Error: 403 Forbidden: @babel/helper-module-imports@7.0.0-beta.35
19 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
19 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
19 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
19 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
19 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
19 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
19 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
19 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
19 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
19 verbose stack     at runCallback (timers.js:781:20)
19 verbose stack     at tryOnImmediate (timers.js:743:5)
19 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
20 verbose cwd /Users/emptywalker/Desktop/MiYa/support-ios/big-data-weex
21 verbose Darwin 16.7.0
22 verbose argv "/usr/local/Cellar/node/8.4.0/bin/node" "/usr/local/bin/npm" "i" "babel-plugin-component" "babel-preset-stage-0" "-D"
23 verbose node v8.4.0
24 verbose npm  v5.5.1
25 error code E403
26 error 403 Forbidden: @babel/helper-module-imports@7.0.0-beta.35
27 verbose exit [ 1, true ]
```

如果直接 npm i weex-ui -S 项目在build的时候报错如下(部分)：
```
 ERROR in ./~/weex-vue-loader/lib/script-loader.js!./~/babel-loader/lib!./~/weex-vue-loader/lib/selector.js?type=script&index=0!./~/weex-ui/packages/wxc-rich-text/wxc-rich-text-tag.vue
    Module build failed: SyntaxError: Unexpected token (96:10)
    
      94 |       if (tagStyle && tagStyle.fontSize) {
      95 |         textStyle = {
    > 96 |           ...textStyle,
         |           ^
      97 |           fontSize: `${tagStyle.fontSize}px`
      98 |         }
      99 |       }
    
     @ ./~/weex-ui/packages/wxc-rich-text/wxc-rich-text-tag.vue 9:18-150
     @ ./~/weex-vue-loader/lib/script-loader.js!./~/babel-loader/lib!./~/weex-vue-loader/lib/selector.js?type=script&index=0!./~/weex-ui/packages/wxc-rich-text/index.vue
     @ ./~/weex-ui/packages/wxc-rich-text/index.vue
     @ ./~/weex-ui/packages/wxc-rich-text/index.js
     @ ./~/weex-ui/index.js
     @ ./~/weex-vue-loader/lib/script-loader.js!./~/babel-loader/lib!./~/weex-vue-loader/lib/selector.js?type=script&index=0!./src/merchants-overview/money-top10.vue
     @ ./src/merchants-overview/money-top10.vue?entry=true
```

请问该如解决 :)

**Comment by tw93** [comment]
你被伟大的墙给拦住了，试试这个https://npm.taobao.org/
