### ISSUE TITLE
wxc-tab-bar set 'is-tab-view' to false gets ActivityNotFoundException error in debugger

### ISSUE THREAD

**Issue by zassq** [alibaba/weex-ui#204]
using wxc-tab-bar, and when `is-tab-view` is set to `false`, I'm receiving a `ActivityNotFoundException` error in the weex debugger

#### wxc-tab-bar is setup like this:
```
<wxc-tab-bar :tab-titles="tabTitles" :tab-styles="tabStyles" title-type="iconFont" wrap-bg-color="transparent" :is-tab-view="false"></wxc-tab-bar>
```

#### tabTitles is like this:
```
[
    {
        codePoint: "\ue62f",
        title: "Search",
        url: `${weex.config.eros.jsServer}/dist/js/pages/home/index.js`,
    },
    {
        codePoint: "\ue65f",
        title: "Bookings",
        url: `${weex.config.eros.jsServer}/dist/js/pages/bookings/index.js`,
    },
    {
        codePoint: "\ue618",
        title: "Freebies",
        url: `${weex.config.eros.jsServer}/dist/js/pages/freebies/index.js`,
    },
    {
        codePoint: "\ue615",
        title: "Me",
        url: `${weex.config.eros.jsServer}/dist/js/pages/profile/index.js`,
    }
]
```

#### error message in weex debugger
```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[com.taobao.android.intent.category.WEEX] dat=http://192.168.3.13:8889/... (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1878)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1545)
	at android.app.Activity.startActivityForResult(Activity.java:4283)
	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
	at android.app.Activity.startActivityForResult(Activity.java:4230)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
	at android.app.Activity.startActivity(Activity.java:4567)
	at android.app.Activity.startActivity(Activity.java:4535)
	at com.taobao.weex.appfram.navigator.WXNavigatorModule.push(WXNavigatorModule.java:132)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.taobao.weex.bridge.MethodInvoker.invoke(MethodInvoker.java:46)
	at com.taobao.weex.bridge.NativeInvokeHelper$1.run(NativeInvokeHelper.java:49)
	at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

The urls are correct as I can open them in the browser

BTW, I'm using weex-ui with eros, but I don't think it should be any issue, as in the source code it seems tabbar jumps out with a call to weex native navigator

Any idea what's wrong with my setup? many thanks....

----
中文版：
wxc-tab-bar 用`is-tab-view`模式在weex debugger里报了`ActivityNotFoundException`错误，求救。。。

**Comment by tw93** [comment]
How about ios show?
Maybe `jump page` has some error

**Comment by zassq** [comment]
We are not implementing ios just yet...暂时木有ios资源。。。

**Comment by tw93** [comment]
Instead of this link test, I think it's a problem for your app container.
<https://h5.m.taobao.com/trip/weex-ui/demo/index.native-min.js>

**Comment by zassq** [comment]
I just tried with the provided link, still got the same error. 
Can you be more specific about the app container?
Thanks.

**Comment by tw93** [comment]
So don't pass in the url and just do it yourself in the   `wxcTabBarCurrentTabSelected ` event.
