### ISSUE TITLE
最新创建项目编译报错

### ISSUE THREAD

**Issue by June0611** [alibaba/weex-ui#93]
Hash: 0ee846b5c14cff2ace2ba3ec637a7a16831e87d2
Version: webpack 2.7.0
Child
    Hash: 0ee846b5c14cff2ace2b
    Time: 4409ms
              Asset      Size  Chunks             Chunk Names
        main.web.js   46.2 kB       0  [emitted]  main
    main.web.js.map  88 bytes       0  [emitted]  main
       [0] ./~/vue-loader/lib/component-normalizer.js 2.55 kB {0} [built]
       [2] ./~/vue-style-loader/lib/addStylesClient.js 6.05 kB {0} [built]
       [3] ./src/index.vue 1.41 kB {0} [built]
       [5] ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/weex-ui/packages/wxc-page-calendar/index.vue 6.28 kB {0} [built]
       [6] ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/index.vue 1.81 kB {0} [built]
       [7] ./~/weex-ui/packages/utils/index.js 9.71 kB {0} [built]
       [8] ./~/weex-ui/packages/wxc-minibar/index.js 362 bytes {0} [built]
       [9] ./~/weex-ui/packages/wxc-page-calendar/format.js 8.85 kB {0} [built]
      [10] ./~/weex-ui/packages/wxc-page-calendar/index.js 362 bytes {0} [built]
      [11] ./src/index.js 336 bytes {0} [built]
      [12] ./~/css-loader?sourceMap!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-2ecae9ec","scoped":true,"hasInlineConfig":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./~/weex-ui/packages/wxc-page-calendar/index.vue 12.8 kB {0} [built]
      [18] ./~/weex-ui/packages/wxc-page-calendar/index.vue 1.75 kB {0} [built]
      [19] ./~/vue-loader/lib/template-compiler?{"id":"data-v-292156ed"}!./~/vue-loader/lib/selector.js?type=template&index=0!./src/index.vue 2.1 kB {0} [built]
      [20] ./~/vue-loader/lib/template-compiler?{"id":"data-v-2ecae9ec"}!./~/vue-loader/lib/selector.js?type=template&index=0!./~/weex-ui/packages/wxc-page-calendar/index.vue 3.35 kB {0} [built]
      [22] ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-2ecae9ec","scoped":true,"hasInlineConfig":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./~/weex-ui/packages/wxc-page-calendar/index.vue 1.5 kB {0} [built]
        + 11 hidden modules
    
    ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/index.vue
    Module not found: Error: Can't resolve 'weex-ui/packages/wxc-page-calendar/style.css' in '/Users/nile/Desktop/weex/weex-ui-test2/src'
     @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/index.vue 11:0-55
     @ ./src/index.vue
     @ ./src/index.js
Child
    Hash: a3ec637a7a16831e87d2
    Time: 4397ms
      Asset     Size  Chunks             Chunk Names
    main.js  25.8 kB       0  [emitted]  main
       [0] ./src/index.vue 1.42 kB {0} [built]
       [1] ./~/weex-ui/packages/utils/index.js 9.71 kB {0} [built]
       [2] ./~/weex-ui/packages/wxc-minibar/index.js 362 bytes {0} [built]
       [3] ./~/weex-ui/packages/wxc-page-calendar/format.js 8.85 kB {0} [built]
       [4] ./~/weex-ui/packages/wxc-page-calendar/index.js 362 bytes {0} [built]
       [5] ./src/index.js 336 bytes {0} [built]
       [7] ./~/url-parse/index.js 11.4 kB {0} [built]
       [8] ./~/url-parse/~/querystringify/index.js 1.51 kB {0} [built]
      [10] ./~/weex-ui/packages/wxc-minibar/index.vue 1.7 kB {0} [built]
      [11] ./~/weex-ui/packages/wxc-page-calendar/index.vue 1.7 kB {0} [built]
      [13] ./~/weex-vue-loader/lib/script-loader.js!./~/babel-loader/lib!./~/weex-vue-loader/lib/selector.js?type=script&index=0!./~/weex-ui/packages/wxc-page-calendar/index.vue 6.28 kB {0} [built]
      [14] ./~/weex-vue-loader/lib/script-loader.js!./~/babel-loader/lib!./~/weex-vue-loader/lib/selector.js?type=script&index=0!./src/index.vue 1.81 kB {0} [built]
      [16] ./~/weex-vue-loader/lib/style-loader.js!./~/weex-vue-loader/lib/style-rewriter.js?id=data-v-8ef13670!./~/weex-vue-loader/lib/selector.js?type=styles&index=0!./~/weex-ui/packages/wxc-page-calendar/index.vue 2.28 kB {0} [built]
      [18] ./~/weex-vue-loader/lib/template-compiler.js?id=data-v-2964abc9!./~/weex-vue-loader/lib/selector.js?type=template&index=0!./src/index.vue 1.2 kB {0} [built]
      [19] ./~/weex-vue-loader/lib/template-compiler.js?id=data-v-8ef13670!./~/weex-vue-loader/lib/selector.js?type=template&index=0!./~/weex-ui/packages/wxc-page-calendar/index.vue 2.17 kB {0} [built]
        + 5 hidden modules
    
    ERROR in ./~/weex-vue-loader/lib/script-loader.js!./~/babel-loader/lib!./~/weex-vue-loader/lib/selector.js?type=script&index=0!./src/index.vue
    Module not found: Error: Can't resolve 'weex-ui/packages/wxc-page-calendar/style.css' in '/Users/nile/Desktop/weex/weex-ui-test2/src'
     @ ./~/weex-vue-loader/lib/script-loader.js!./~/babel-loader/lib!./~/weex-vue-loader/lib/selector.js?type=script&index=0!./src/index.vue 11:0-55
     @ ./src/index.vue
     @ ./src/index.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! weex@1.0.0 build: `webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the weex@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tt/.npm/_logs/2017-12-19T07_10_47_168Z-debug.log

#######  2017-12-19T07_10_47_168Z-debug.log

13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:885:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid weex@1.0.0
15 verbose cwd /Users/nile/Desktop/weex/weex-ui-test2
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run-script" "build"
18 verbose node v7.4.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error weex@1.0.0 build: `webpack`
22 error Exit status 2
23 error Failed at the weex@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

以前创建项目没有问题

**Comment by tw93** [comment]
> npm i
